"""initial

Revision ID: 41dcacc7071c
Revises: 
Create Date: 2026-02-19 09:28:42.431779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41dcacc7071c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_date', 'from_currency', 'to_currency', name='uq_daily_rate')
    )
    op.create_index('ix_currency_rate_date', 'currency_rates', ['rate_date'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('brainsuite_apps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('app_type', sa.String(length=50), nullable=False),
    sa.Column('is_default_for_video', sa.Boolean(), nullable=False),
    sa.Column('is_default_for_image', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadata_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('business_unit', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('two_factor_secret', sa.Text(), nullable=True),
    sa.Column('is_two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('metadata_field_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['metadata_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('brainsuite_app_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('ad_account_id', sa.String(length=255), nullable=False),
    sa.Column('ad_account_name', sa.String(length=500), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connection_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_metadata_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initial_sync_completed', sa.Boolean(), nullable=False),
    sa.Column('historical_sync_completed', sa.Boolean(), nullable=False),
    sa.Column('historical_sync_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brainsuite_app_id'], ['brainsuite_apps.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('creative_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('platform_connection_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('ad_id', sa.String(length=255), nullable=False),
    sa.Column('ad_name', sa.String(length=1000), nullable=True),
    sa.Column('ad_set_id', sa.String(length=255), nullable=True),
    sa.Column('ad_set_name', sa.String(length=1000), nullable=True),
    sa.Column('campaign_id', sa.String(length=255), nullable=True),
    sa.Column('campaign_name', sa.String(length=1000), nullable=True),
    sa.Column('campaign_objective', sa.String(length=255), nullable=True),
    sa.Column('ad_account_id', sa.String(length=255), nullable=True),
    sa.Column('creative_id', sa.String(length=255), nullable=True),
    sa.Column('asset_format', sa.String(length=50), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('asset_url', sa.Text(), nullable=True),
    sa.Column('video_duration', sa.Float(), nullable=True),
    sa.Column('placement', sa.String(length=255), nullable=True),
    sa.Column('platform_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ace_score', sa.Float(), nullable=True),
    sa.Column('ace_score_confidence', sa.String(length=50), nullable=True),
    sa.Column('brainsuite_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'platform', 'ad_id', 'ad_account_id', name='uq_creative_asset')
    )
    op.create_table('sync_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform_connection_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_metadata_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['creative_assets.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['metadata_fields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'field_id', name='uq_asset_metadata_field')
    )
    op.create_table('asset_project_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['creative_assets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'project_id', name='uq_asset_project')
    )
    op.create_table('harmonized_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('platform_connection_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('ad_account_id', sa.String(length=255), nullable=False),
    sa.Column('campaign_id', sa.String(length=255), nullable=True),
    sa.Column('campaign_name', sa.String(length=1000), nullable=True),
    sa.Column('campaign_objective', sa.String(length=255), nullable=True),
    sa.Column('ad_set_id', sa.String(length=255), nullable=True),
    sa.Column('ad_set_name', sa.String(length=1000), nullable=True),
    sa.Column('ad_id', sa.String(length=255), nullable=False),
    sa.Column('ad_name', sa.String(length=1000), nullable=True),
    sa.Column('asset_format', sa.String(length=50), nullable=True),
    sa.Column('org_currency', sa.String(length=3), nullable=False),
    sa.Column('original_currency', sa.String(length=3), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('spend', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('cpm', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('conversion_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cvr', sa.Float(), nullable=True),
    sa.Column('roas', sa.Float(), nullable=True),
    sa.Column('video_views', sa.Integer(), nullable=True),
    sa.Column('vtr', sa.Float(), nullable=True),
    sa.Column('video_completion_rate', sa.Float(), nullable=True),
    sa.Column('cost_per_view', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('platform_extras', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('harmonized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['creative_assets.id'], ),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_connection_id', 'report_date', 'ad_id', 'ad_account_id', name='uq_harmonized_daily_ad')
    )
    op.create_index('ix_harmonized_asset', 'harmonized_performance', ['asset_id'], unique=False)
    op.create_index('ix_harmonized_date', 'harmonized_performance', ['report_date'], unique=False)
    op.create_index('ix_harmonized_platform', 'harmonized_performance', ['platform'], unique=False)
    op.create_table('meta_raw_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform_connection_id', sa.UUID(), nullable=False),
    sa.Column('sync_job_id', sa.UUID(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('ad_account_id', sa.String(length=255), nullable=False),
    sa.Column('campaign_id', sa.String(length=255), nullable=True),
    sa.Column('campaign_name', sa.String(length=1000), nullable=True),
    sa.Column('campaign_objective', sa.String(length=255), nullable=True),
    sa.Column('ad_set_id', sa.String(length=255), nullable=True),
    sa.Column('ad_set_name', sa.String(length=1000), nullable=True),
    sa.Column('ad_id', sa.String(length=255), nullable=False),
    sa.Column('ad_name', sa.String(length=1000), nullable=True),
    sa.Column('creative_id', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('ad_format', sa.String(length=100), nullable=True),
    sa.Column('placement', sa.String(length=255), nullable=True),
    sa.Column('targeting_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('spend', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('cpm', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('conversion_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cvr', sa.Float(), nullable=True),
    sa.Column('roas', sa.Float(), nullable=True),
    sa.Column('video_views', sa.Integer(), nullable=True),
    sa.Column('video_view_rate', sa.Float(), nullable=True),
    sa.Column('estimated_ad_recall_lift', sa.Float(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], ),
    sa.ForeignKeyConstraint(['sync_job_id'], ['sync_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_connection_id', 'report_date', 'ad_id', 'ad_account_id', name='uq_meta_daily_ad')
    )
    op.create_index('ix_meta_raw_ad_id', 'meta_raw_performance', ['ad_id'], unique=False)
    op.create_index('ix_meta_raw_date_account', 'meta_raw_performance', ['report_date', 'ad_account_id'], unique=False)
    op.create_table('tiktok_raw_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform_connection_id', sa.UUID(), nullable=False),
    sa.Column('sync_job_id', sa.UUID(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('ad_account_id', sa.String(length=255), nullable=False),
    sa.Column('campaign_id', sa.String(length=255), nullable=True),
    sa.Column('campaign_name', sa.String(length=1000), nullable=True),
    sa.Column('campaign_objective', sa.String(length=255), nullable=True),
    sa.Column('ad_group_id', sa.String(length=255), nullable=True),
    sa.Column('ad_group_name', sa.String(length=1000), nullable=True),
    sa.Column('ad_id', sa.String(length=255), nullable=False),
    sa.Column('ad_name', sa.String(length=1000), nullable=True),
    sa.Column('creative_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('ad_format', sa.String(length=100), nullable=True),
    sa.Column('targeting_segment', sa.String(length=500), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('spend', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cpm', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('conversion_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cvr', sa.Float(), nullable=True),
    sa.Column('roas', sa.Float(), nullable=True),
    sa.Column('video_views', sa.Integer(), nullable=True),
    sa.Column('video_completion_rate', sa.Float(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('swipe_rate', sa.Float(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], ),
    sa.ForeignKeyConstraint(['sync_job_id'], ['sync_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_connection_id', 'report_date', 'ad_id', 'ad_account_id', name='uq_tiktok_daily_ad')
    )
    op.create_index('ix_tiktok_raw_ad_id', 'tiktok_raw_performance', ['ad_id'], unique=False)
    op.create_index('ix_tiktok_raw_date_account', 'tiktok_raw_performance', ['report_date', 'ad_account_id'], unique=False)
    op.create_table('youtube_raw_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform_connection_id', sa.UUID(), nullable=False),
    sa.Column('sync_job_id', sa.UUID(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('ad_account_id', sa.String(length=255), nullable=False),
    sa.Column('campaign_id', sa.String(length=255), nullable=True),
    sa.Column('campaign_name', sa.String(length=1000), nullable=True),
    sa.Column('campaign_objective', sa.String(length=255), nullable=True),
    sa.Column('ad_group_id', sa.String(length=255), nullable=True),
    sa.Column('ad_group_name', sa.String(length=1000), nullable=True),
    sa.Column('ad_id', sa.String(length=255), nullable=False),
    sa.Column('ad_name', sa.String(length=1000), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('video_duration', sa.Integer(), nullable=True),
    sa.Column('placement_type', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('spend', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cpm', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('conversion_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('cvr', sa.Float(), nullable=True),
    sa.Column('roas', sa.Float(), nullable=True),
    sa.Column('view_rate', sa.Float(), nullable=True),
    sa.Column('cost_per_view', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('earned_views', sa.Integer(), nullable=True),
    sa.Column('video_view_through_rate', sa.Float(), nullable=True),
    sa.Column('video_quartile_p25', sa.Float(), nullable=True),
    sa.Column('video_quartile_p50', sa.Float(), nullable=True),
    sa.Column('video_quartile_p75', sa.Float(), nullable=True),
    sa.Column('video_quartile_p100', sa.Float(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], ),
    sa.ForeignKeyConstraint(['sync_job_id'], ['sync_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_connection_id', 'report_date', 'ad_id', 'ad_account_id', name='uq_youtube_daily_ad')
    )
    op.create_index('ix_youtube_raw_ad_id', 'youtube_raw_performance', ['ad_id'], unique=False)
    op.create_index('ix_youtube_raw_date_account', 'youtube_raw_performance', ['report_date', 'ad_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_youtube_raw_date_account', table_name='youtube_raw_performance')
    op.drop_index('ix_youtube_raw_ad_id', table_name='youtube_raw_performance')
    op.drop_table('youtube_raw_performance')
    op.drop_index('ix_tiktok_raw_date_account', table_name='tiktok_raw_performance')
    op.drop_index('ix_tiktok_raw_ad_id', table_name='tiktok_raw_performance')
    op.drop_table('tiktok_raw_performance')
    op.drop_index('ix_meta_raw_date_account', table_name='meta_raw_performance')
    op.drop_index('ix_meta_raw_ad_id', table_name='meta_raw_performance')
    op.drop_table('meta_raw_performance')
    op.drop_index('ix_harmonized_platform', table_name='harmonized_performance')
    op.drop_index('ix_harmonized_date', table_name='harmonized_performance')
    op.drop_index('ix_harmonized_asset', table_name='harmonized_performance')
    op.drop_table('harmonized_performance')
    op.drop_table('asset_project_mappings')
    op.drop_table('asset_metadata_values')
    op.drop_table('sync_jobs')
    op.drop_table('creative_assets')
    op.drop_table('refresh_tokens')
    op.drop_table('projects')
    op.drop_table('platform_connections')
    op.drop_table('organization_roles')
    op.drop_table('metadata_field_values')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('metadata_fields')
    op.drop_table('brainsuite_apps')
    op.drop_table('organizations')
    op.drop_index('ix_currency_rate_date', table_name='currency_rates')
    op.drop_table('currency_rates')
    # ### end Alembic commands ###
